// subgraphs-network-exporter — serve The Graph network subgraph's on-chain indexer economics as
// Prometheus metrics.
//
// Stake, delegation, allocations and curation signal live in the network subgraph (GraphQL), not in
// any /metrics endpoint. We query it every REFRESH_SECONDS and expose:
//   • per-indexer gauges  — self-stake, delegated, delegation capacity, allocated, available stake,
//                            lifetime query fees & rewards, capacity-used ratio  (labelled by wallet)
//   • per-(indexer,deployment) allocation — indexer_subgraph_allocated_grt
//   • per-deployment network-wide — subgraph_total_allocated_grt (all indexers), subgraph_signalled_grt
//     (curation signal, drives the indexing-reward split), subgraph_name_info (display name)
//
// Two scopes:
//   INDEXERS          — the DETAIL set (default ours): full stake + allocations + signal + names.
//   ALL_INDEXER_STAKE — also emit stake gauges for EVERY registered indexer with > MIN_STAKE_GRT
//                       staked, via one batched query (stake only — allocations stay scoped to INDEXERS
//                       so we never fan out hundreds of per-indexer queries at graph-node).
//
// Indexer display names come from a committed indexers.json (baked into the image), regenerated
// out-of-band by scripts/gen-indexers.ts — no risky runtime name field on the critical path.
//
// Metric names are unchanged from the old inline stake-exporter (plus an indexer/indexer_name label on
// the per-deployment allocation), so Grafana keeps working. Zero npm deps — Bun's global fetch. Pure
// render/format helpers are exported for `bun test`.

// The network subgraph GraphQL endpoint. Default is our in-cluster GNArb deployment (only resolves
// inside the cluster); override for local testing.
const NETWORK_SUBGRAPH_URL = (process.env.NETWORK_SUBGRAPH_URL ??
  "http://graph-node-serve.subgraphs-arbitrum-one:8000/subgraphs/id/QmT329Bej8AwSLahmgnmi6fdYkj3rorYAcCes45gDv9aJ4"
).replace(/\/+$/, "");
// Detail set — comma-separated wallets. Default: our indexer. Each gets full stake + allocation +
// signal + name treatment.
const INDEXERS = (process.env.INDEXERS ?? "0x3717cef8020bddee7a18f4efb2bfa88fefdcb1bc")
  .split(",").map((s) => s.trim().toLowerCase()).filter(Boolean);
// Also export stake gauges for EVERY registered indexer over the min-stake floor (network-wide view).
const ALL_INDEXER_STAKE = (process.env.ALL_INDEXER_STAKE ?? "false").toLowerCase() === "true";
const MIN_STAKE_GRT = Number(process.env.MIN_STAKE_GRT ?? 100000);   // floor for the all-indexers view
const MIN_STAKE_WEI = (BigInt(Math.max(0, Math.round(MIN_STAKE_GRT))) * 10n ** 18n).toString();
const REFRESH_MS = Number(process.env.REFRESH_SECONDS ?? 60) * 1000;
const NAME_REFRESH_MS = Number(process.env.NAME_REFRESH_SECONDS ?? 1800) * 1000;   // names change rarely
const PORT = Number(process.env.PORT ?? 9400);

// Indexer wallet → display name, from the committed JSON (regenerated by scripts/gen-indexers.ts).
// Optional: a missing file just leaves indexer_name blank. Keys lowercased for lookup.
const INDEXERS_FILE = process.env.INDEXERS_FILE ?? "indexers.json";
let indexerNames: Record<string, string> = {};
try {
  const raw = (await Bun.file(INDEXERS_FILE).json()) as Record<string, string>;
  indexerNames = Object.fromEntries(Object.entries(raw).map(([k, v]) => [k.toLowerCase(), v]));
} catch { /* optional */ }
const nameOf = (id: string) => indexerNames[id.toLowerCase()] ?? "";
console.log(`loaded ${Object.keys(indexerNames).length} indexer names from ${INDEXERS_FILE}`);

// ── GraphQL ──────────────────────────────────────────────────────────────────────────────────────
async function gql(query: string): Promise<any> {
  const r = await fetch(NETWORK_SUBGRAPH_URL, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ query }),
  });
  if (!r.ok) throw new Error(`gql HTTP ${r.status}`);
  const j = (await r.json()) as { data?: any; errors?: unknown };
  if (j.errors) throw new Error(`gql: ${JSON.stringify(j.errors)}`);
  return j.data;
}

// Only fields the previous (proven-live) exporter used — no name field on the critical path.
// indexingRewardCut (ppm) feeds the delegator-APY panels: delegators receive (1 - cut) of rewards.
const STAKE_FIELDS = "stakedTokens delegatedTokens delegatedCapacity allocatedTokens availableStake " +
  "queryFeesCollected rewardsEarned thawingTokens delegatedThawingTokens indexingRewardCut";
// Network-wide reward parameters — one tiny query. Gross-GRT/day for an indexer =
// reward_index * issuance_per_block * blocks_per_day / total_signal (see the rewards dashboard row).
const networkQuery =
  `{ graphNetworks(first:1){ totalTokensSignalled networkGRTIssuancePerBlock } }`;
// One batched query for the explicit detail set (id_in) — no min-stake floor: an explicitly-tracked
// indexer (e.g. ours) always shows, whatever its stake.
const stakeListQuery = (ids: string[]) =>
  `{ indexers(first:1000, where:{id_in:[${ids.map((i) => `"${i}"`).join(",")}]}){ id ${STAKE_FIELDS} } }`;
// One batched query for every registered indexer above the stake floor (network-wide view).
const stakeAllQuery = (minWei: string) =>
  `{ indexers(first:1000, orderBy:stakedTokens, orderDirection:desc, where:{stakedTokens_gt:"${minWei}"}){ id ${STAKE_FIELDS} } }`;
const allocQuery = (id: string) =>
  `{ indexer(id:"${id}"){ allocations(first:1000, where:{status:Active}){ ` +
  `allocatedTokens subgraphDeployment { ipfsHash stakedTokens signalledTokens ` +
  // full active-allocation set on each deployment → count distinct indexers (network-wide, from the
  // network subgraph — populated even when the gateway QoS feed has no data for the subgraph).
  `indexerAllocations(first:1000, where:{status:Active}){ indexer { id } } } } } }`;
const nameQuery = (id: string) =>
  `{ indexer(id:"${id}"){ allocations(first:1000, where:{status:Active}){ subgraphDeployment { ipfsHash ` +
  `versions(first:1, orderBy:version, orderDirection:desc){ subgraph { metadata { displayName } } } } } } }`;

// ── formatting ───────────────────────────────────────────────────────────────────────────────────
// wei string → GRT float. BigInt keeps the integer exact before the (lossy-but-fine) /1e18 divide.
export const grt = (v: unknown): number => {
  try { return Number(BigInt(String(v ?? "0"))) / 1e18; } catch { return 0; }
};
export const esc = (s: unknown): string =>
  String(s ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, " ");

// [metric, GraphQL key, HELP text]
const FIELDS: [string, string, string][] = [
  ["indexer_self_stake_grt", "stakedTokens", "Indexer self-stake"],
  ["indexer_delegated_grt", "delegatedTokens", "Delegated tokens"],
  ["indexer_delegation_capacity_grt", "delegatedCapacity", "Delegation capacity (16x self-stake)"],
  ["indexer_allocated_grt", "allocatedTokens", "Allocated tokens"],
  ["indexer_available_stake_grt", "availableStake", "Available (unallocated) stake"],
  ["indexer_query_fees_collected_grt", "queryFeesCollected", "Lifetime query fees collected"],
  ["indexer_rewards_earned_grt", "rewardsEarned", "Lifetime indexing rewards earned"],
  // Thawing = tokens in the 28-day undelegation/unstake lock. delegated_thawing is the early-warning
  // signal for delegator exits (e.g. 197.8k thawing 2026-07: three delegators, two full exits) —
  // availableStake already nets it out, so this is the ONLY place the outflow is visible pre-withdrawal.
  ["indexer_self_thawing_grt", "thawingTokens", "Indexer self-stake currently thawing (unstake lock)"],
  ["indexer_delegated_thawing_grt", "delegatedThawingTokens", "Delegated tokens currently thawing (undelegation lock)"],
];

export type StakeRow = { id: string; name: string; data: Record<string, unknown> };
export type AllocRow = { indexer: string; indexerName: string; hash: string; allocated: number };
export type DeploymentAgg = { total: number; signal: number; indexers: number };

export function renderStake(rows: StakeRow[]): string {
  const out: string[] = [];
  for (const [metric, , help] of FIELDS) out.push(`# HELP ${metric} ${help} (GRT)`, `# TYPE ${metric} gauge`);
  out.push("# HELP indexer_capacity_used_ratio Allocated / delegation capacity (0-1)",
    "# TYPE indexer_capacity_used_ratio gauge",
    "# HELP indexer_indexing_reward_cut_ratio Share of indexing rewards the indexer keeps (0-1); delegators get the rest",
    "# TYPE indexer_indexing_reward_cut_ratio gauge");
  for (const row of rows) {
    const lbl = `indexer="${esc(row.id)}",indexer_name="${esc(row.name)}"`;
    for (const [metric, key] of FIELDS) out.push(`${metric}{${lbl}} ${grt(row.data[key]).toFixed(6)}`);
    const cap = grt(row.data.delegatedCapacity), alloc = grt(row.data.allocatedTokens);
    out.push(`indexer_capacity_used_ratio{${lbl}} ${(cap ? alloc / cap : 0).toFixed(6)}`);
    // indexingRewardCut is ppm (plain int, NOT wei)
    out.push(`indexer_indexing_reward_cut_ratio{${lbl}} ${(Number(row.data.indexingRewardCut ?? 0) / 1e6).toFixed(6)}`);
  }
  return out.join("\n") + "\n";
}

export function renderNetwork(net: { totalTokensSignalled?: unknown; networkGRTIssuancePerBlock?: unknown }): string {
  return ["# HELP graph_network_total_signal_grt Total curation signal across the ENTIRE network (GRT)",
    "# TYPE graph_network_total_signal_grt gauge",
    `graph_network_total_signal_grt ${grt(net.totalTokensSignalled).toFixed(6)}`,
    "# HELP graph_network_issuance_per_block_grt Network GRT issuance per block (GRT)",
    "# TYPE graph_network_issuance_per_block_grt gauge",
    `graph_network_issuance_per_block_grt ${grt(net.networkGRTIssuancePerBlock).toFixed(6)}`,
  ].join("\n") + "\n";
}

export function renderAlloc(allocs: AllocRow[]): string {
  // sum multiple active allocations by the same indexer on the same deployment
  const agg = new Map<string, { indexer: string; name: string; hash: string; v: number }>();
  for (const a of allocs) {
    const k = `${a.indexer}|${a.hash}`;
    const cur = agg.get(k) ?? { indexer: a.indexer, name: a.indexerName, hash: a.hash, v: 0 };
    cur.v += a.allocated;
    agg.set(k, cur);
  }
  const out = ["# HELP indexer_subgraph_allocated_grt An indexer's active allocation on this deployment (GRT)",
    "# TYPE indexer_subgraph_allocated_grt gauge"];
  for (const { indexer, name, hash, v } of agg.values())
    out.push(`indexer_subgraph_allocated_grt{indexer="${esc(indexer)}",indexer_name="${esc(name)}",deployment="${esc(hash)}"} ${v.toFixed(6)}`);
  return out.join("\n") + "\n";
}

export function renderDeployments(deps: Map<string, DeploymentAgg>): string {
  const out = ["# HELP subgraph_total_allocated_grt Tokens allocated on this deployment by ALL indexers (GRT)",
    "# TYPE subgraph_total_allocated_grt gauge",
    "# HELP subgraph_signalled_grt Curation signal on this deployment (GRT) - drives indexing-reward split",
    "# TYPE subgraph_signalled_grt gauge",
    "# HELP subgraph_indexer_count Number of indexers with an active allocation on this deployment (network subgraph)",
    "# TYPE subgraph_indexer_count gauge"];
  for (const [hash, d] of deps) out.push(`subgraph_total_allocated_grt{deployment="${esc(hash)}"} ${d.total.toFixed(6)}`);
  for (const [hash, d] of deps) out.push(`subgraph_signalled_grt{deployment="${esc(hash)}"} ${d.signal.toFixed(6)}`);
  for (const [hash, d] of deps) out.push(`subgraph_indexer_count{deployment="${esc(hash)}"} ${d.indexers}`);
  return out.join("\n") + "\n";
}

export function renderNames(names: Map<string, string>): string {
  const out = ["# HELP subgraph_name_info deployment -> real subgraph display name",
    "# TYPE subgraph_name_info gauge"];
  for (const [hash, name] of names) out.push(`subgraph_name_info{deployment="${esc(hash)}",name="${esc(name)}"} 1`);
  return out.join("\n") + "\n";
}

// ── runtime state ────────────────────────────────────────────────────────────────────────────────
let stakeBlock = "", allocBlock = "", depBlock = "", nameBlock = "", netBlock = "";
let up = 0, lastRefresh = 0, trackedCount = 0, deploymentCount = 0;

async function refreshEconomics(): Promise<void> {
  let stakeOk = false, allocOk = false, tracked = 0;
  // network-wide reward parameters (total signal + issuance) — non-fatal if it blips
  try {
    const net = (await gql(networkQuery))?.graphNetworks?.[0];
    if (net) netBlock = renderNetwork(net);
  } catch (e) { console.error(`network: ${e}`); }
  // stake — ONE batched query for the target set (detail list, or every indexer over the floor)
  try {
    const q = ALL_INDEXER_STAKE ? stakeAllQuery(MIN_STAKE_WEI) : stakeListQuery(INDEXERS);
    const idx = (await gql(q))?.indexers ?? [];
    const rows: StakeRow[] = idx.map((d: any) => {
      const id = String(d.id).toLowerCase();
      return { id, name: nameOf(id), data: d };
    });
    if (rows.length) { stakeBlock = renderStake(rows); tracked = rows.length; stakeOk = true; }
  } catch (e) { console.error(`stake: ${e}`); }

  // allocations + signal — per-indexer over the DETAIL set only (bounded fan-out)
  const allocs: AllocRow[] = [];
  const deps = new Map<string, DeploymentAgg>();
  let allocErr = 0;
  for (const id of INDEXERS) {
    try {
      const al = (await gql(allocQuery(id)))?.indexer?.allocations ?? [];
      const iname = nameOf(id);
      for (const a of al) {
        const sd = a.subgraphDeployment ?? {};
        const hash = sd.ipfsHash;
        if (!hash) continue;
        allocs.push({ indexer: id, indexerName: iname, hash, allocated: grt(a.allocatedTokens) });
        // distinct indexers with an active allocation on this deployment (network-wide)
        const ixs = new Set((sd.indexerAllocations ?? []).map((x: any) => x?.indexer?.id).filter(Boolean));
        deps.set(hash, { total: grt(sd.stakedTokens), signal: grt(sd.signalledTokens), indexers: ixs.size });
      }
    } catch (e) { console.error(`alloc ${id}: ${e}`); allocErr++; }
  }
  if (allocErr < INDEXERS.length) {
    allocBlock = renderAlloc(allocs);
    depBlock = renderDeployments(deps);
    deploymentCount = deps.size;
    allocOk = true;
  }

  if (stakeOk) trackedCount = tracked;
  up = stakeOk || allocOk ? 1 : 0;
  lastRefresh = Math.floor(Date.now() / 1000);
  if (up) console.log(`refreshed: stake_indexers=${tracked}, allocations=${allocs.length}, deployments=${deploymentCount}`);
  else console.error("refresh failed (stake query + every allocation query)");
}

async function refreshNames(): Promise<void> {
  const names = new Map<string, string>();
  for (const id of INDEXERS) {
    try {
      const al = (await gql(nameQuery(id)))?.indexer?.allocations ?? [];
      for (const a of al) {
        const sd = a.subgraphDeployment ?? {};
        const hash = sd.ipfsHash;
        if (!hash || names.has(hash)) continue;
        let nm = "";
        for (const v of sd.versions ?? []) {
          const dn = v?.subgraph?.metadata?.displayName;
          if (dn) { nm = dn; break; }
        }
        names.set(hash, nm || hash);   // fall back to hash if unnamed
      }
    } catch (e) { console.error(`names ${id}: ${e}`); }
  }
  if (names.size) nameBlock = renderNames(names);
}

function body(): string {
  return stakeBlock + allocBlock + depBlock + nameBlock + netBlock +
    "# TYPE subgraphs_network_exporter_up gauge\n" + `subgraphs_network_exporter_up ${up}\n` +
    "# TYPE subgraphs_network_exporter_last_refresh_seconds gauge\n" + `subgraphs_network_exporter_last_refresh_seconds ${lastRefresh}\n` +
    "# TYPE subgraphs_network_exporter_indexers_tracked gauge\n" + `subgraphs_network_exporter_indexers_tracked ${trackedCount}\n` +
    "# TYPE subgraphs_network_exporter_deployments_tracked gauge\n" + `subgraphs_network_exporter_deployments_tracked ${deploymentCount}\n` +
    // backward-compat with the old inline exporter's liveness metric
    "# TYPE indexer_stake_exporter_up gauge\n" + `indexer_stake_exporter_up ${up}\n`;
}

if (import.meta.main) {
  // Fast-retry (30s) after a failure so a transient GraphQL blip never leaves us stale for long and
  // never fails a k8s rollout (readiness gates on /healthz → the first good refresh).
  (async function loop() { await refreshEconomics(); setTimeout(loop, up ? REFRESH_MS : 30_000); })();
  (async function nloop() { await refreshNames(); setTimeout(nloop, NAME_REFRESH_MS); })();

  Bun.serve({
    port: PORT,
    fetch(req) {
      const path = new URL(req.url).pathname;
      if (path === "/metrics" || path === "/")
        return new Response(body(), { headers: { "content-type": "text/plain; version=0.0.4" } });
      if (path === "/healthz")
        return new Response(up ? "ok" : "degraded", { status: up ? 200 : 503 });
      return new Response("not found", { status: 404 });
    },
  });
  console.log(`network-exporter on :${PORT} — subgraph=${NETWORK_SUBGRAPH_URL} detail=[${INDEXERS.join(", ")}]` +
    ` all_indexer_stake=${ALL_INDEXER_STAKE}${ALL_INDEXER_STAKE ? ` (>${MIN_STAKE_GRT} GRT)` : ""} refresh=${REFRESH_MS / 1000}s`);
}
